//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Визит.
    /// </summary>
    // *** Start programmer edit section *** (Визит CustomAttributes)

    // *** End programmer edit section *** (Визит CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВизитE", new string[] {
            "Код as \'Код\'",
            "время as \'Время\'",
            "Времяр as \'Времяр\'",
            "Клиент as \'Клиент\'",
            "Клиент.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Клиент.ФИО"})]
    [AssociatedDetailViewAttribute("ВизитE", "ЗаписьВизита", "ЗаписьВизитаE", true, "", "Запись визита", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ВизитE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ВизитL", new string[] {
            "Код as \'Код\'",
            "время as \'Время\'",
            "Времяр as \'Времяр\'",
            "Клиент.ФИО as \'ФИО\'"})]
    public class Визит : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fвремя;
        
        private System.DateTime fВремяр;
        
        private IIS.Bekap_2.Клиент fКлиент;
        
        private IIS.Bekap_2.DetailArrayOfЗаписьВизита fЗаписьВизита;
        
        // *** Start programmer edit section *** (Визит CustomMembers)

        // *** End programmer edit section *** (Визит CustomMembers)

        
        /// <summary>
        /// время.
        /// </summary>
        // *** Start programmer edit section *** (Визит.время CustomAttributes)

        // *** End programmer edit section *** (Визит.время CustomAttributes)
        public virtual System.DateTime время
        {
            get
            {
                // *** Start programmer edit section *** (Визит.время Get start)

                // *** End programmer edit section *** (Визит.время Get start)
                System.DateTime result = this.fвремя;
                // *** Start programmer edit section *** (Визит.время Get end)

                // *** End programmer edit section *** (Визит.время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.время Set start)

                // *** End programmer edit section *** (Визит.время Set start)
                this.fвремя = value;
                // *** Start programmer edit section *** (Визит.время Set end)

                // *** End programmer edit section *** (Визит.время Set end)
            }
        }
        
        /// <summary>
        /// Времяр.
        /// </summary>
        // *** Start programmer edit section *** (Визит.Времяр CustomAttributes)

        // *** End programmer edit section *** (Визит.Времяр CustomAttributes)
        public virtual System.DateTime Времяр
        {
            get
            {
                // *** Start programmer edit section *** (Визит.Времяр Get start)

                // *** End programmer edit section *** (Визит.Времяр Get start)
                System.DateTime result = this.fВремяр;
                // *** Start programmer edit section *** (Визит.Времяр Get end)

                // *** End programmer edit section *** (Визит.Времяр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.Времяр Set start)

                // *** End programmer edit section *** (Визит.Времяр Set start)
                this.fВремяр = value;
                // *** Start programmer edit section *** (Визит.Времяр Set end)

                // *** End programmer edit section *** (Визит.Времяр Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Визит.Код CustomAttributes)

        // *** End programmer edit section *** (Визит.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Визит.Код Get start)

                // *** End programmer edit section *** (Визит.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Визит.Код Get end)

                // *** End programmer edit section *** (Визит.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.Код Set start)

                // *** End programmer edit section *** (Визит.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Визит.Код Set end)

                // *** End programmer edit section *** (Визит.Код Set end)
            }
        }
        
        /// <summary>
        /// Визит.
        /// </summary>
        // *** Start programmer edit section *** (Визит.Клиент CustomAttributes)

        // *** End programmer edit section *** (Визит.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Bekap_2.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Визит.Клиент Get start)

                // *** End programmer edit section *** (Визит.Клиент Get start)
                IIS.Bekap_2.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Визит.Клиент Get end)

                // *** End programmer edit section *** (Визит.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.Клиент Set start)

                // *** End programmer edit section *** (Визит.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Визит.Клиент Set end)

                // *** End programmer edit section *** (Визит.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Визит.
        /// </summary>
        // *** Start programmer edit section *** (Визит.ЗаписьВизита CustomAttributes)

        // *** End programmer edit section *** (Визит.ЗаписьВизита CustomAttributes)
        public virtual IIS.Bekap_2.DetailArrayOfЗаписьВизита ЗаписьВизита
        {
            get
            {
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Get start)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Get start)
                if ((this.fЗаписьВизита == null))
                {
                    this.fЗаписьВизита = new IIS.Bekap_2.DetailArrayOfЗаписьВизита(this);
                }
                IIS.Bekap_2.DetailArrayOfЗаписьВизита result = this.fЗаписьВизита;
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Get end)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Set start)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Set start)
                this.fЗаписьВизита = value;
                // *** Start programmer edit section *** (Визит.ЗаписьВизита Set end)

                // *** End programmer edit section *** (Визит.ЗаписьВизита Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВизитE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВизитE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВизитE", typeof(IIS.Bekap_2.Визит));
                }
            }
            
            /// <summary>
            /// "ВизитL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВизитL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВизитL", typeof(IIS.Bekap_2.Визит));
                }
            }
        }
    }
}
