//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [Caption("Клиенты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "ФИО as \'ФИО\'",
            "Номер as \'Номер\'",
            "Пол as \'Пол\'"})]
    [View("КлиентL", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "ФИО as \'ФИО\'",
            "Номер as \'Номер\'",
            "Пол as \'Пол\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fДата;
        
        private string fФИО;
        
        private int fНомер;
        
        private string fmail;
        
        private IIS.Bekap_2.Пол fПол;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// mail.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.mail CustomAttributes)

        // *** End programmer edit section *** (Клиент.mail CustomAttributes)
        [StrLen(255)]
        private string mail
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.mail Get start)

                // *** End programmer edit section *** (Клиент.mail Get start)
                string result = this.fmail;
                // *** Start programmer edit section *** (Клиент.mail Get end)

                // *** End programmer edit section *** (Клиент.mail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.mail Set start)

                // *** End programmer edit section *** (Клиент.mail Set start)
                this.fmail = value;
                // *** Start programmer edit section *** (Клиент.mail Set end)

                // *** End programmer edit section *** (Клиент.mail Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Дата CustomAttributes)

        // *** End programmer edit section *** (Клиент.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Дата Get start)

                // *** End programmer edit section *** (Клиент.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Клиент.Дата Get end)

                // *** End programmer edit section *** (Клиент.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Дата Set start)

                // *** End programmer edit section *** (Клиент.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Клиент.Дата Set end)

                // *** End programmer edit section *** (Клиент.Дата Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Код CustomAttributes)

        // *** End programmer edit section *** (Клиент.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Код Get start)

                // *** End programmer edit section *** (Клиент.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Клиент.Код Get end)

                // *** End programmer edit section *** (Клиент.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Код Set start)

                // *** End programmer edit section *** (Клиент.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Клиент.Код Set end)

                // *** End programmer edit section *** (Клиент.Код Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Номер CustomAttributes)

        // *** End programmer edit section *** (Клиент.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Номер Get start)

                // *** End programmer edit section *** (Клиент.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Клиент.Номер Get end)

                // *** End programmer edit section *** (Клиент.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Номер Set start)

                // *** End programmer edit section *** (Клиент.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Клиент.Номер Set end)

                // *** End programmer edit section *** (Клиент.Номер Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.Пол CustomAttributes)

        // *** End programmer edit section *** (Клиент.Пол CustomAttributes)
        public virtual IIS.Bekap_2.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.Пол Get start)

                // *** End programmer edit section *** (Клиент.Пол Get start)
                IIS.Bekap_2.Пол result = this.fПол;
                // *** Start programmer edit section *** (Клиент.Пол Get end)

                // *** End programmer edit section *** (Клиент.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.Пол Set start)

                // *** End programmer edit section *** (Клиент.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (Клиент.Пол Set end)

                // *** End programmer edit section *** (Клиент.Пол Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ФИО Get start)

                // *** End programmer edit section *** (Клиент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиент.ФИО Get end)

                // *** End programmer edit section *** (Клиент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ФИО Set start)

                // *** End programmer edit section *** (Клиент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиент.ФИО Set end)

                // *** End programmer edit section *** (Клиент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.Bekap_2.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.Bekap_2.Клиент));
                }
            }
        }
    }
}
