//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пол.
    /// </summary>
    // *** Start programmer edit section *** (Пол CustomAttributes)

    // *** End programmer edit section *** (Пол CustomAttributes)
    public enum Пол
    {
        
        // *** Start programmer edit section *** (Пол.Мужской CustomAttributes)

        // *** End programmer edit section *** (Пол.Мужской CustomAttributes)
        Мужской,
        
        // *** Start programmer edit section *** (Пол.Женский CustomAttributes)

        // *** End programmer edit section *** (Пол.Женский CustomAttributes)
        Женский,
    }
}
