//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Bekap_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Производитель as \'Производитель\'",
            "товара as \'Товара\'",
            "мат as \'Мат\'"})]
    [View("ТоварL", new string[] {
            "Производитель as \'Производитель\'",
            "товара as \'Товара\'",
            "мат as \'Мат\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private string fПроизводитель;
        
        private int fтовара;
        
        private string fмат;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// мат.
        /// </summary>
        // *** Start programmer edit section *** (Товар.мат CustomAttributes)

        // *** End programmer edit section *** (Товар.мат CustomAttributes)
        [StrLen(255)]
        public virtual string мат
        {
            get
            {
                // *** Start programmer edit section *** (Товар.мат Get start)

                // *** End programmer edit section *** (Товар.мат Get start)
                string result = this.fмат;
                // *** Start programmer edit section *** (Товар.мат Get end)

                // *** End programmer edit section *** (Товар.мат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.мат Set start)

                // *** End programmer edit section *** (Товар.мат Set start)
                this.fмат = value;
                // *** Start programmer edit section *** (Товар.мат Set end)

                // *** End programmer edit section *** (Товар.мат Set end)
            }
        }
        
        /// <summary>
        /// Производитель.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Производитель CustomAttributes)

        // *** End programmer edit section *** (Товар.Производитель CustomAttributes)
        [StrLen(255)]
        public virtual string Производитель
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Производитель Get start)

                // *** End programmer edit section *** (Товар.Производитель Get start)
                string result = this.fПроизводитель;
                // *** Start programmer edit section *** (Товар.Производитель Get end)

                // *** End programmer edit section *** (Товар.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Производитель Set start)

                // *** End programmer edit section *** (Товар.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (Товар.Производитель Set end)

                // *** End programmer edit section *** (Товар.Производитель Set end)
            }
        }
        
        /// <summary>
        /// товара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.товара CustomAttributes)

        // *** End programmer edit section *** (Товар.товара CustomAttributes)
        public virtual int товара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.товара Get start)

                // *** End programmer edit section *** (Товар.товара Get start)
                int result = this.fтовара;
                // *** Start programmer edit section *** (Товар.товара Get end)

                // *** End programmer edit section *** (Товар.товара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.товара Set start)

                // *** End programmer edit section *** (Товар.товара Set start)
                this.fтовара = value;
                // *** Start programmer edit section *** (Товар.товара Set end)

                // *** End programmer edit section *** (Товар.товара Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Bekap_2.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Bekap_2.Товар));
                }
            }
        }
    }
}
